### ISSUE TITLE
Add a copy of the MIT license to the repository

### ISSUE THREAD

**Issue by Calinou** [SYBIOTE/Godot-Mesh-slicer#1]
The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this :slightly_smiling_face:

**Comment by SYBIOTE** [comment]
yeah forgot that , thanks for reminding me

**Comment by SYBIOTE** [comment]
and its done

**Comment by Calinou** [comment]
Thanks! The asset is now approved: https://godotengine.org/asset-library/asset/938
