### ISSUE TITLE
Missing plugin.cfg file

### ISSUE THREAD

**Issue by lewiji** [SYBIOTE/Godot-Mesh-slicer#4]
Hi,

This seems like a nice addon! But I can't get it to work and I think it's because it's missing a `plugin.cfg` file defining the plugin.

As it is I can't enable the plugin in the Project Settings menu.

I also tried merging the `_global_script_classes` from this repo into my `project.godot` file but still could not access the `sliceable` node.

**Comment by SYBIOTE** [comment]
its not a plugin , its a node , check the demo file

**Comment by lewiji** [comment]
The README suggests to me that a custom node is added to the "Create New Node" dialog under "RigidBody", however in the demo project or by installing from the asset store this doesn't happen for me.

I can manually add the script to my RigidBody but it'd be convenient to be able to add it using the dialog.

I see that your script uses the `class_name` keyword which registers it as a script class - I've not used this before, but the docs suggest this should make the node come up in the "Create New Node", but it doesn't for me (on 3.3.x or 3.4b)

For example I am using another addon called MeshBatcher that's a custom node rather than plugin. With that when I install it from the AssetLib the new "MeshBatcher" node appears under MultiMeshInstance in the new node dialog:

![image](https://user-images.githubusercontent.com/233380/132546123-b82be020-fef7-487e-bb49-b6900add52e2.png)

That addon has a `plugin.cfg` file that loads the main .gd file, which then uses `add_custom_type`  function to register its script as a node:

https://github.com/OrigamiDev-Pete/MeshBatcher/blob/master/addons/MultiMeshBatcher/plugin.cfg

https://github.com/OrigamiDev-Pete/MeshBatcher/blob/master/addons/MultiMeshBatcher/Batcher.gd#L13

However since you're using scriptable class I'm not sure if the same approach is needed, my thought was that if a `plugin.cfg` file was added that referenced that script then it would be automatically added to the creation dialog, but I am not sure, do you know?

**Comment by lewiji** [comment]
BTW I got it working anyway! Apparently the issue is that Godot ignores `class_name` if the script is in the `addons` folder. So I moved it out of the addons folder and now it works perfectly :)

Man the cross section texture is a great touch :D
